# -------------------------------------------------------------------------------
# Trivy Scan Worker - Build and Push
#
# Project: Nomad Temporal Jobs / Author: Alex Freidah
#
# Sets this worker's image name and package, then includes the shared build
# rules in ../_common.mk.
# -------------------------------------------------------------------------------

IMAGE := trivy-scan-worker
PKG   := trivyscan

include ../_common.mk
