# -------------------------------------------------------------------------------
# Node Cleanup Worker - Build and Push
#
# Project: Nomad Temporal Jobs / Author: Alex Freidah
#
# Sets this worker's image name, package, and runtime profile, then includes
# the shared build rules in ../_common.mk.
# -------------------------------------------------------------------------------

IMAGE          := cleanup-worker
PKG            := nodecleanup
RUNTIME_TARGET := runtime-distroless-root

include ../_common.mk
