# -------------------------------------------------------------------------------
# Backup Worker - Build and Push
#
# Project: Nomad Temporal Jobs / Author: Alex Freidah
#
# Sets this worker's image name and package, then includes the shared build
# rules in ../_common.mk.
# -------------------------------------------------------------------------------

IMAGE := backup-worker
PKG   := backup

include ../_common.mk
