# -------------------------------------------------------------------------------
# Backup Worker - Build and Push
#
# Project: Nomad Temporal Jobs / Author: Alex Freidah
#
# Sets this worker's image name, package, and runtime profile, then includes
# the shared build rules in ../_common.mk.
# -------------------------------------------------------------------------------

IMAGE          := backup-worker
PKG            := backup
RUNTIME_TARGET := runtime-backup

include ../_common.mk
