# -------------------------------------------------------------------------------
# Cert Acquirer Worker - Build and Push
#
# Project: Nomad Temporal Jobs / Author: Alex Freidah
#
# Sets this worker's image name, package, and runtime profile, then includes
# the shared build rules in ../_common.mk.
# -------------------------------------------------------------------------------

IMAGE          := cert-acquirer-worker
PKG            := certacquirer
RUNTIME_TARGET := runtime-distroless-nonroot

include ../_common.mk
