# -------------------------------------------------------------------------------
# Cert Acquirer Worker - Build and Push
#
# Project: Nomad Temporal Jobs / Author: Alex Freidah
#
# Sets this worker's image name and package, then includes the shared build
# rules in ../_common.mk.
# -------------------------------------------------------------------------------

IMAGE := cert-acquirer-worker
PKG   := certacquirer

include ../_common.mk
